add weather variable
stape-io/weather-variable pull request #1
Opened 2024-02-15 15:51 UTC by dmtsolovey

2024-02-15 15:52 UTC, kHorozhanov commented on template.js
> +        return "We couldn't determine your city";
return null

2024-02-15 15:52 UTC, kHorozhanov commented on template.js
> +
if !city return null

2024-02-15 15:53 UTC, kHorozhanov commented on template.js
> +    return sendHttpRequest(url).then((successResult) => {
rename successResult to response

2024-02-15 15:54 UTC, kHorozhanov commented on template.js
> +            return sendRequest(successResult);
add logs like in Http varable

2024-02-16 16:47 UTC, Bukashk0zzz approved these changes

2024-02-16 16:47 UTC, Bukashk0zzz commented on LICENSE
> +   Copyright 2022 Stape
2024

2024-02-16 16:47 UTC, Bukashk0zzz commented on metadata.yaml
> +homepage: 'https://stape.io/'
do not commit this file before this PR will not merged.
remove this file from this PR

2024-02-16 16:47 UTC, Bukashk0zzz commented on template.js
> +    const cityFromHeaders = getRequestHeader('X-Geo-City');
There need to be ability to choose in UI from with parameter get City and Country
By default get from Stape headers  but provide ability to override this.

2024-02-16 16:47 UTC, Bukashk0zzz commented on template.js
> +const url = apiUrl + "q=" + enc(city) + "&appid=" + enc(apiKey) + "&units=" + enc(units);
look like it good Idea to provide country also as one city can be in multiple countries.

2024-02-16 16:48 UTC, Bukashk0zzz requested changes
Changes

2024-02-22 15:10 UTC, Bukashk0zzz requested changes
@kHorozhanov review also.

2024-02-22 15:10 UTC, Bukashk0zzz commented on metadata.yaml
Remove this file from PR

2024-02-22 15:10 UTC, Bukashk0zzz commented on template.js
> +    const cityFromHeaders = getRequestHeader('X-Geo-City') || data.city;
data.city || getRequestHeader('X-Geo-City') change order.a

2024-02-22 15:10 UTC, Bukashk0zzz commented on template.js
> +    const countryFromHeaders = getRequestHeader('X-Geo-Country') || data.countryCode || '';
data.countryCode || getRequestHeader('X-Geo-Country') change order

2024-02-22 15:10 UTC, Bukashk0zzz commented on template.js
> +const geoCountry = geo.country ? ',' + geo.country : '';
You already checked at this moment if country exist

2024-02-22 15:28 UTC, merged